/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:76624b01-6947-4759-be87-194569b6cddb",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_HjE5IUmdQ",
    "aws_user_pools_web_client_id": "1vlft2oue6qpd43f8fmjjca0ad",
    "oauth": {}
};


export default awsmobile;
